# Helm config
mixer:
  gcpProjectID: datcom-mixer-dev-316822
  serviceName: dev.api.datacommons.org

ingress:
  enabled: true
  name: mixer-ingress-dev
  annotations:
    {
      kubernetes.io/ingress.global-static-ip-name: mixer-ip,
      ingress.gcp.kubernetes.io/pre-shared-cert: mixer-certificate,
    }

# GCP level config
ip: 35.244.157.41
region: us-central1
api_title: DataCommons API (Dev)
nodes: 2
