# Helm config
mixer:
  gcpProjectID: datcom-mixer-staging
  serviceName: staging.api.datacommons.org

ingress:
  enabled: true
  name: mixer-ingress-staging
  annotations:
    {
      ingress.gcp.kubernetes.io/pre-shared-cert: "mixer-certificate,multi-domain-2022",
    }

serviceGroups:
  - svg:
      urlPaths:
        - "/place/stat-var-group/*"
        - "/stat-var/*"
        - "/v1/info/variable-group/*"
        - "/v1/variable/*"
        - "/v1/bulk/info/variable-group"
        - "/v1/bulk/info/variable"
      replicas:
        default: 2
        min: 2
        max: 8
      resources:
        memoryRequest: "8G"
        memoryLimit: "8G"
      useSearch: true
  - recon:
      urlPaths:
        - "/v1/recon/*"
      replicas:
        default: 10
        min: 10
        max: 20
      resources:
        memoryRequest: "400M"
        memoryLimit: "400M"
  - observation:
      urlPaths:
        - "/v1/observations/*"
        - "/v1/bulk/observations/*"
      replicas:
        default: 10
        min: 10
        max: 20
      resources:
        memoryRequest: "4G"
        memoryLimit: "4G"
  - default:
      urlPaths:
        - "/*"
      replicas:
        default: 10
        min: 10
        max: 20
      resources:
        memoryRequest: "3G"
        memoryLimit: "3G"

# GCP level config
ip: 34.107.161.252
region: us-central1
api_title: DataCommons API (Staging)
nodes: 2
