# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for mixer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name of the Chart.
nameOverride: ""
# Full name of the release in the following format.
# <release name>-<chart name>
fullnameOverride: ""

# Namespace for the deployment.
# Set enabled to false to deploy into an existing namespace.
namespace:
  create: false
  name: "mixer"

# Mixer service config.
mixer:
  gcpProjectID:
  githash:

  useTMCFCSVData: false
  # Name of the GCS bucket without scheme.
  # Example: datcom-public
  tmcfCSVBucket:
  # Folder under the CSV bucket.
  tmcfCSVFolder:

  # If bigqueryOnly is True, bigqueryTableRef must be specified.
  bigqueryOnly: false
  # Example: google.com:datcom-store-dev.dc_v3_encode_clustered
  bigqueryTableRef:

  # URL root for the mixer service launched.
  # Example: dev.api.datacommons.org
  serviceName:

  image:
    repository: gcr.io/datcom-ci/datacommons-mixer
    pullPolicy: IfNotPresent
    tag: "latest"

  schemaConfigs:
    base.mcf:
    encode.mcf:

esp:
  image:
    repository: gcr.io/endpoints-release/endpoints-runtime
    pullPolicy: IfNotPresent
    tag: "1"

# Config for k8s-sa(service account). The k8s-sa will be bound to a
# GCP-sa using annotations, specified below.
serviceAccount:
  create: false
  # K8s service account name.
  name: mixer-ksa
  # Google service account name.
  gsaName: mixer-robot

ingress:
  name:
  enabled: true
  annotations:
    {
      kubernetes.io/ingress.global-static-ip-name: mixer-ip,
      ingress.gcp.kubernetes.io/pre-shared-cert: mixer-certificate,
    }

kgStoreConfig:
  bigqueryVersion:
  baseBigtableInfo: ""
  customBigtableInfo: ""

memdbJSON: ""

# To overwrite any portion of serviceGroups, please copy and paste
# the entire serviceGroups below into the custom values yaml file,
# and make changes to it.
serviceGroups:
  - svg:
      urlPaths:
        - "/place/stat-var-group/*"
        - "/stat-var/*"
        - "/v1/info/variable-group/*"
        - "/v1/variable/*"
        - "/v1/bulk/info/variable-group"
        - "/v1/bulk/info/variable"
      replicas:
        default: 2
        min: 2
        max: 2
      resources:
        memoryRequest: "8G"
        memoryLimit: "8G"
      useSearch: true
    # If the name of the recon service is changed here,
    # please also change the name in the deployment.yaml template.
  - recon:
      urlPaths:
        - "/v1/recon/*"
      replicas:
        default: 4
        min: 4
        max: 4
      resources:
        memoryRequest: "400M"
        memoryLimit: "400M"
  - observation:
      urlPaths:
        - "/v1/observations/*"
        - "/v1/bulk/observations/*"
      replicas:
        default: 4
        min: 4
        max: 4
      resources:
        memoryRequest: "4G"
        memoryLimit: "4G"
  - default:
      urlPaths:
        - "/*"
      replicas:
        default: 4
        min: 4
        max: 4
      resources:
        memoryRequest: "4G"
        memoryLimit: "4G"
