steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/datcom-ci/deploy-tool:${_TAG}', '.' ]
images:
- 'gcr.io/datcom-ci/deploy-tool:${_TAG}'
substitutions:
    _TAG: "latest"
