# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Kustomization for local mixer in local Minikube environment.
# - Adds "local" suffix to all the resources
# - Use "serviceaccount.yaml" to create service account explicitly.
#   Note the GKE cluster service account is created once at cluster creation time.
# - Patch deployment with "api-compiler" image that can updates the gRPC config on code change.
# - Update the esp startup options for local container.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mixer

bases:
  - ../mapping
  - ../storage

resources:
  - deployment.yaml

configMapGenerator:
  - name: mixer-configmap
    behavior: create
    literals:
      - mixerProject=datcom-mixer-dev-316822
      - serviceName=
  - behavior: merge
    name: store-configmap
    files:
      - custom_bigtable_info.yaml

generatorOptions:
  disableNameSuffixHash: true
